version: "3.2"

services:
  drupal:
    # Specify a name for your Docker image to be tagged with, this should
    # ideally be under whatever namespace your images will be stored under
    # for consistency. We use the tag "local" here so that it is easily
    # distinguished from images our CD tool builds.
    #
    # Note, that if you were to not define a build configuration then Docker
    # would not create an image and simply try to retrieve the image from any
    # registry you've configured (default hub.docker.com).
    #
    # See .drone.yml
    image: aaadigital/drupal-starter:local
    # Define how the image should be built.
    build:
      # See ./drupal/Dockerfile
      context: ./drupal
    networks:
      - default
      # Shared network used to connect to Træfik container.
      - shared
    labels:
      # Træfik configuration is managed via these labels.
      - "traefik.docker.network=shared"
      - "traefik.backend=drupal"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:drupal.localhost"
    # Note this container does not make use of any bind mounts from the local
    # machine. To update the image with new code you'd need to rebuild.

  drupal_dev:
    # To support development tools such as Xdebug, a separate image is used
    # durig live development.
    #
    # See drupal-dev/Dockerfile
    image: aaadigital/drupal-starter:dev
    depends_on:
      - drupal
    build:
      context: ./drupal-dev
      args:
        UPSTREAM_TAG: local
    networks:
      - default
      - shared
    labels:
      - "traefik.docker.network=shared"
      - "traefik.backend=drupal-dev"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:dev.drupal.localhost"
    volumes:
      - type: volume
        source: drupal-config-volume
        target: /var/www/config
      - type: volume
        source: drupal-html-volume
        target: /var/www/html

  # Drupal has too many files for bind sync's to be used, even delegated.
  # See https://docs.docker.com/docker-for-mac/osxfs-caching/
  #
  # Instead we use https://hub.docker.com/r/codycraven/quick-bind-sync/
  drupal_config_sync:
    image: codycraven/quick-bind-sync:0.1.0
    depends_on:
      - drupal_dev
    volumes:
      - type: bind
        source: ./drupal/config
        target: /host
      - type: volume
        source: drupal-config-volume
        target: /volume
  drupal_html_sync:
    image: codycraven/quick-bind-sync:0.1.0
    depends_on:
      - drupal_dev
    volumes:
      - type: bind
        source: ./drupal/html
        target: /host
      - type: volume
        source: drupal-html-volume
        target: /volume

volumes:
  drupal-config-volume:
  drupal-html-volume:

networks:
  # The shared network is created in the README.md requisites.
  shared:
    external: true
