version: "3.2"

services:
  drupal:
    # Specify a name for your Docker image to be tagged with, this should
    # ideally be under whatever namespace your images will be stored under.
    # See .drone.yml
    image: aaadigital/drupal-starter
    # Define how the image should be built.
    build:
      context: ./drupal
